"use client";

import React from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { StatsCounter } from "@/components/common/StatsCounter";
import {
  TrendingUp,
  Bot,
  Search,
  ArrowRight,
  LineChart,
  BrainCircuit,
  Terminal,
  Activity,
  Layers,
} from "lucide-react";

export default function Home() {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.1,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 15 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { duration: 0.5, ease: [0.215, 0.61, 0.355, 1] as const },
    },
  };

  const features = [
    {
      title: "AI Insights",
      description:
        "Instant tactical match assessments, team transition weights, and pressing trigger profiles generated by Gemini AI.",
      icon: BrainCircuit,
    },
    {
      title: "Interactive Graphs",
      description:
        "Beautiful pass networks, spatial clusters, and player telemetry plots rendered directly in high fidelity.",
      icon: LineChart,
    },
    {
      title: "Team Analytics",
      description:
        "Deep dives into squad average defensive lines, zone control ratings, and possession phase efficiency.",
      icon: Layers,
    },
    {
      title: "Natural Language Search",
      description:
        "Query your database in plain English. Get instant stats, player grids, and direct tactical answers.",
      icon: Search,
    },
  ];

  return (
    <div className="relative min-h-screen bg-[#070708] text-zinc-100 overflow-x-hidden font-sans antialiased selection:bg-emerald-500/20 selection:text-emerald-400">
      {/* Top Subtle Green Spotlight Glow */}
      <div className="absolute top-[-250px] left-1/2 -translate-x-1/2 w-[800px] h-[500px] bg-emerald-500/5 blur-[160px] pointer-events-none rounded-full" />

      {/* Minimal Sticky Navbar */}
      <header className="sticky top-0 z-50 w-full bg-[#070708]/75 backdrop-blur-md border-b border-zinc-900/60">
        <div className="max-w-7xl mx-auto flex items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2 group">
            <div className="w-7 h-7 rounded bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-500 transition-colors group-hover:bg-emerald-500/20">
              <TrendingUp className="w-3.5 h-3.5" />
            </div>
            <span className="font-semibold tracking-tight text-white text-sm">
              FutGraph <span className="text-emerald-500">AI</span>
            </span>
          </Link>

          <nav className="hidden md:flex items-center gap-8 text-xs font-medium text-zinc-400">
            <Link href="/dashboard" className="hover:text-white transition-colors">
              Dashboard
            </Link>
            <Link href="/dashboard/analytics" className="hover:text-white transition-colors">
              Analytics
            </Link>
            <a href="#" className="hover:text-white transition-colors">
              Docs
            </a>
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1.5 hover:text-white transition-colors"
            >
              <svg className="w-3.5 h-3.5 fill-current" viewBox="0 0 16 16">
                <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z" />
              </svg>
              <span>GitHub</span>
            </a>
          </nav>

          <div className="flex items-center gap-4">
            <Link
              href="/dashboard"
              className="text-xs text-zinc-400 hover:text-white transition-colors font-medium"
            >
              Sign In
            </Link>
            <Link
              href="/dashboard"
              className="text-xs bg-zinc-100 hover:bg-zinc-200 text-zinc-950 px-3.5 py-1.5 rounded-lg font-medium transition-colors"
            >
              Explore Dashboard
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative w-full max-w-7xl mx-auto px-6 pt-20 pb-28">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-16 items-center">
          {/* Hero Left Content */}
          <motion.div
            initial="hidden"
            animate="visible"
            variants={containerVariants}
            className="lg:col-span-5 space-y-8 text-left"
          >
            <motion.div
              variants={itemVariants}
              className="inline-flex items-center gap-2 bg-zinc-950 border border-zinc-900 px-3 py-1 rounded-full text-[11px] text-zinc-400 font-mono"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" />
              <span>FIFA World Cup 2026 Dataset Active</span>
            </motion.div>

            <div className="space-y-4">
              <motion.h1
                variants={itemVariants}
                className="text-4xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-white leading-[1.1]"
              >
                Understand Football.
                <br />
                <span className="text-zinc-500">Through Data.</span>
              </motion.h1>

              <motion.p
                variants={itemVariants}
                className="text-sm sm:text-base text-zinc-400 leading-relaxed max-w-md"
              >
                Interactive football analytics powered by AI. Transform telemetry and raw match logs
                into tactical charts, radars, and automated insights.
              </motion.p>
            </div>

            <motion.div variants={itemVariants} className="flex items-center gap-3.5">
              <Link
                href="/dashboard"
                className="bg-emerald-500 hover:bg-emerald-600 text-zinc-950 px-5 py-2.5 rounded-lg font-medium text-xs transition-all shadow-[0_0_20px_-5px_rgba(34,197,94,0.4)] hover:shadow-[0_0_25px_-5px_rgba(34,197,94,0.6)] flex items-center gap-1.5"
              >
                <span>Explore Dashboard</span>
                <ArrowRight className="w-3.5 h-3.5" />
              </Link>
              <a
                href="https://github.com"
                target="_blank"
                rel="noopener noreferrer"
                className="bg-zinc-950 hover:bg-zinc-900 border border-zinc-900 hover:border-zinc-800 text-zinc-200 px-4 py-2.5 rounded-lg font-medium text-xs transition-colors flex items-center gap-1.5"
              >
                <svg className="w-4 h-4 fill-zinc-400" viewBox="0 0 16 16">
                  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z" />
                </svg>
                <span>GitHub</span>
              </a>
            </motion.div>
          </motion.div>

          {/* Hero Right Mockup with Emerald Green Glow */}
          <motion.div
            initial={{ opacity: 0, scale: 0.98 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
            className="lg:col-span-7 relative"
          >
            {/* Glow backing the card */}
            <div className="absolute inset-0 bg-emerald-500/5 blur-[80px] rounded-3xl pointer-events-none z-0" />

            {/* Dashboard Mockup Window */}
            <div className="relative z-10 border border-zinc-900 bg-[#0d0d0f]/80 backdrop-blur rounded-2xl shadow-[0_25px_60px_-15px_rgba(0,0,0,0.8),0_0_40px_-15px_rgba(34,197,94,0.1)] overflow-hidden">
              {/* Window Header bar */}
              <div className="flex items-center justify-between px-5 py-3.5 border-b border-zinc-900/60 bg-zinc-950/40">
                <div className="flex items-center gap-1.5">
                  <span className="w-2.5 h-2.5 rounded-full bg-zinc-800" />
                  <span className="w-2.5 h-2.5 rounded-full bg-zinc-800" />
                  <span className="w-2.5 h-2.5 rounded-full bg-zinc-800" />
                  <span className="text-[10px] text-zinc-500 font-mono ml-3 select-none">
                    futgraph-shell // telemetry-view
                  </span>
                </div>
                <div className="flex items-center gap-1 px-2 py-0.5 rounded bg-zinc-900/70 border border-zinc-800/40 text-[9px] text-zinc-400 font-mono">
                  <Terminal className="w-2.5 h-2.5 text-emerald-500" />
                  <span>ACTIVE</span>
                </div>
              </div>

              {/* Mockup Layout Content */}
              <div className="p-5 grid grid-cols-1 md:grid-cols-12 gap-5">
                {/* Simulated Tactical Pitch Grid (8 Cols) */}
                <div className="md:col-span-8 bg-[#070709] border border-zinc-900/60 rounded-xl p-4 relative overflow-hidden h-[240px] flex items-center justify-center">
                  {/* Pitch Green Grid overlay */}
                  <div className="absolute inset-0 opacity-[0.02] bg-[radial-gradient(#22C55E_1px,transparent_1px)] [background-size:12px_12px]" />

                  {/* Simulated Football Pitch Outline */}
                  <div className="absolute inset-2 border border-zinc-900/40 rounded flex items-center justify-center">
                    <div className="absolute inset-y-0 left-0 w-8 border-r border-zinc-900/30 flex items-center justify-start">
                      <div className="h-20 w-4 border-y border-r border-zinc-900/30" />
                    </div>
                    <div className="absolute inset-y-0 right-0 w-8 border-l border-zinc-900/30 flex items-center justify-end">
                      <div className="h-20 w-4 border-y border-l border-zinc-900/30" />
                    </div>
                    <div className="w-px h-full bg-zinc-900/20 absolute left-1/2" />
                    <div className="w-16 h-16 rounded-full border border-zinc-900/20 absolute left-1/2 -translate-x-1/2" />
                  </div>

                  {/* Pass map nodes & lines (SVG overlay) */}
                  <svg className="absolute inset-0 w-full h-full text-emerald-500/30" viewBox="0 0 300 200">
                    {/* passing arcs */}
                    <path
                      d="M 60 70 Q 140 40 220 50"
                      fill="none"
                      stroke="url(#passGrad)"
                      strokeWidth="1.5"
                      className="opacity-75"
                    />
                    <path
                      d="M 60 70 Q 110 130 150 150"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1"
                      strokeDasharray="3 3"
                    />
                    <path
                      d="M 150 150 Q 200 110 220 50"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.2"
                    />
                    <path
                      d="M 150 150 Q 220 160 260 110"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="1.5"
                      className="opacity-60"
                    />

                    {/* Gradient definition */}
                    <defs>
                      <linearGradient id="passGrad" x1="0%" y1="0%" x2="100%" y2="100%">
                        <stop offset="0%" stopColor="#22C55E" stopOpacity="0.8" />
                        <stop offset="100%" stopColor="#FFFFFF" stopOpacity="0.2" />
                      </linearGradient>
                    </defs>

                    {/* Player nodes */}
                    <circle cx="60" cy="70" r="4.5" className="fill-emerald-500 shadow-sm" />
                    <circle cx="150" cy="150" r="4.5" className="fill-zinc-400" />
                    <circle cx="220" cy="50" r="4.5" className="fill-emerald-400" />
                    <circle cx="260" cy="110" r="4.5" className="fill-zinc-600" />

                    {/* Zone indicators */}
                    <path
                      d="M 190 30 L 250 30 L 240 90 L 180 80 Z"
                      fill="#22C55E"
                      fillOpacity="0.04"
                      stroke="#22C55E"
                      strokeOpacity="0.15"
                      strokeWidth="1"
                    />
                  </svg>

                  {/* Floating Telemetry Tags */}
                  <div className="absolute top-4 left-4 bg-zinc-950/70 border border-zinc-900 px-2 py-1 rounded text-[8px] font-mono text-zinc-500">
                    LATENCY: 14ms
                  </div>
                  <div className="absolute bottom-4 right-4 bg-zinc-950/70 border border-zinc-900 px-2 py-1 rounded text-[9px] font-mono text-emerald-400 flex items-center gap-1 select-none">
                    <Activity className="w-2.5 h-2.5 animate-pulse" />
                    <span>OVERLOAD ZONE</span>
                  </div>
                </div>

                {/* Simulated Stats Feed (4 Cols) */}
                <div className="md:col-span-4 flex flex-col justify-between gap-4">
                  {/* AI insights output card */}
                  <div className="bg-[#070709] border border-zinc-900/60 rounded-xl p-3.5 space-y-2 text-left">
                    <div className="flex items-center gap-1 text-[9px] font-mono font-bold text-emerald-500 uppercase">
                      <Bot className="w-3 h-3" />
                      <span>Gemini Assessment</span>
                    </div>
                    <p className="text-[10px] text-zinc-400 leading-normal">
                      "Attacking transition filters through #10, shifting focus to high-completion channels inside half-spaces."
                    </p>
                  </div>

                  {/* Live xG counter */}
                  <div className="bg-[#070709] border border-zinc-900/60 rounded-xl p-3.5 space-y-2 text-left">
                    <span className="text-[9px] font-mono text-zinc-500 uppercase">Expected Goals (xG)</span>
                    <div className="flex items-baseline justify-between font-mono">
                      <span className="text-xl font-bold text-white">2.84</span>
                      <span className="text-[9px] text-zinc-600">vs</span>
                      <span className="text-xl font-bold text-zinc-500">1.12</span>
                    </div>
                    {/* xG bar */}
                    <div className="w-full h-1 bg-zinc-900 rounded-full overflow-hidden flex">
                      <div className="h-full bg-emerald-500" style={{ width: "70%" }} />
                      <div className="h-full bg-zinc-700" style={{ width: "30%" }} />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="relative w-full max-w-7xl mx-auto px-6 py-12 border-y border-zinc-900/40 bg-zinc-950/20">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-4 text-center">
          <div className="space-y-1.5">
            <h3 className="text-2xl sm:text-3xl font-bold tracking-tight text-white font-mono">
              <StatsCounter value={64} />
            </h3>
            <p className="text-[10px] text-zinc-500 font-mono uppercase tracking-wider">Matches Analyzed</p>
          </div>
          <div className="space-y-1.5">
            <h3 className="text-2xl sm:text-3xl font-bold tracking-tight text-white font-mono">
              <StatsCounter value={736} />
            </h3>
            <p className="text-[10px] text-zinc-500 font-mono uppercase tracking-wider">Players Tracked</p>
          </div>
          <div className="space-y-1.5">
            <h3 className="text-2xl sm:text-3xl font-bold tracking-tight text-white font-mono">
              <StatsCounter value={32} />
            </h3>
            <p className="text-[10px] text-zinc-500 font-mono uppercase tracking-wider">Teams Indexed</p>
          </div>
          <div className="space-y-1.5">
            <h3 className="text-2xl sm:text-3xl font-bold tracking-tight text-white font-mono">
              <StatsCounter value={1000000} suffix="+" />
            </h3>
            <p className="text-[10px] text-zinc-500 font-mono uppercase tracking-wider">Events Parsed</p>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="w-full max-w-7xl mx-auto px-6 py-28 text-center space-y-16">
        <div className="space-y-3 max-w-xl mx-auto">
          <h2 className="text-2xl sm:text-3xl font-bold tracking-tight text-white">
            Designed for Tactical Engineering
          </h2>
          <p className="text-xs sm:text-sm text-zinc-500">
            A premium analytical platform providing deep insights, spatial graphing, and language-driven metrics.
          </p>
        </div>

        {/* 2x2 Feature Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 text-left max-w-5xl mx-auto">
          {features.map((feature, i) => {
            const Icon = feature.icon;
            return (
              <div
                key={i}
                className="group relative bg-zinc-950/40 border border-zinc-900/75 hover:border-zinc-800 rounded-2xl p-6 transition-all hover:shadow-[0_0_30px_-15px_rgba(34,197,94,0.15)] flex gap-5"
              >
                <div className="w-10 h-10 rounded-xl bg-zinc-900 border border-zinc-800/60 flex items-center justify-center text-zinc-400 group-hover:text-emerald-500 group-hover:border-emerald-500/20 transition-all shrink-0">
                  <Icon className="w-4.5 h-4.5" />
                </div>
                <div className="space-y-1.5">
                  <h3 className="text-sm font-semibold text-white tracking-tight">
                    {feature.title}
                  </h3>
                  <p className="text-xs text-zinc-400 leading-relaxed">
                    {feature.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </section>

      {/* Footer */}
      <footer className="w-full max-w-7xl mx-auto px-6 py-12 border-t border-zinc-900/60">
        <div className="flex flex-col sm:flex-row items-center justify-between text-xs text-zinc-600 gap-4">
          <div className="flex items-center gap-2 select-none">
            <span className="font-semibold text-zinc-300">FutGraph AI</span>
            <span>&copy; {new Date().getFullYear()} Athletico Analytics. All rights reserved.</span>
          </div>
          <div className="flex gap-6">
            <a href="#" className="hover:text-zinc-300 transition-colors">
              Privacy
            </a>
            <a href="#" className="hover:text-zinc-300 transition-colors">
              Terms
            </a>
            <a
              href="https://github.com"
              target="_blank"
              rel="noopener noreferrer"
              className="hover:text-zinc-300 transition-colors"
            >
              GitHub
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
